# Generated by Django 3.2.3 on 2021-10-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='dtg',
            field=models.TimeField(auto_now=True),
        ),
    ]
