# Generated by Django 3.2.3 on 2021-10-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0002_alter_park_dtg'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='klr',
            field=models.TimeField(auto_now=True),
        ),
    ]
