# Generated by Django 3.2.3 on 2021-10-22 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0003_auto_20211021_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notempat', models.TextField(default='', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='ket',
            name='notempat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blok', to='tiket.blok'),
        ),
    ]
