# Generated by Django 3.2.3 on 2021-10-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0003_park_klr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='klr',
        ),
    ]
