# Generated by Django 3.2.3 on 2021-10-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0004_auto_20211022_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blok',
            name='notempat',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='park',
            name='nopol',
            field=models.CharField(default='', max_length=10),
        ),
    ]
