# Generated by Django 3.2.3 on 2021-10-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0005_auto_20211022_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blok',
            old_name='notempat',
            new_name='noblok',
        ),
        migrations.RenameField(
            model_name='ket',
            old_name='notempat',
            new_name='noblok',
        ),
    ]
