# Generated by Django 3.2.3 on 2021-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0006_alter_park_noblok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noblok', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='park',
            name='noblok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blok', to='tiket.blok'),
        ),
    ]
