# Generated by Django 3.2.3 on 2021-10-31 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0009_alter_park_noblok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='dtg',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
